name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'

jobs:
  build-and-deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "prince0127"
          password: "Docker@27."
          # SECURITY WARNING: It is highly recommended to use secrets for passwords!
          # password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t prince0127/frontend-app:latest .

      - name: Push Frontend Docker image
        run: |
          docker push prince0127/frontend-app:latest

      - name: Stop and remove old frontend container (if exists)
        run: |
          if [ "$(docker ps -aq -f name=frontend-container)" ]; then
            docker stop frontend-container
            docker rm frontend-container
          fi

      - name: Run Frontend Docker container
        run: |
          docker run -d --name frontend-container -p 5173:5173 prince0127/frontend-app:latest
